# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RecursionView.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Titletext = QtWidgets.QLabel(self.centralwidget)
        self.Titletext.setGeometry(QtCore.QRect(330, 30, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        self.Titletext.setFont(font)
        self.Titletext.setObjectName("Titletext")
        self.powerButton = QtWidgets.QRadioButton(self.centralwidget)
        self.powerButton.setGeometry(QtCore.QRect(150, 350, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.powerButton.setFont(font)
        self.powerButton.setObjectName("powerButton")
        self.catButton = QtWidgets.QRadioButton(self.centralwidget)
        self.catButton.setGeometry(QtCore.QRect(350, 350, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.catButton.setFont(font)
        self.catButton.setObjectName("catButton")
        self.alienButton = QtWidgets.QRadioButton(self.centralwidget)
        self.alienButton.setGeometry(QtCore.QRect(570, 350, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alienButton.setFont(font)
        self.alienButton.setObjectName("alienButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 430, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 220, 451, 101))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.firstEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.firstEntry.setGeometry(QtCore.QRect(170, 110, 491, 31))
        self.firstEntry.setObjectName("firstEntry")
        self.firstEntrylabel = QtWidgets.QLabel(self.centralwidget)
        self.firstEntrylabel.setGeometry(QtCore.QRect(40, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.firstEntrylabel.setFont(font)
        self.firstEntrylabel.setObjectName("firstEntrylabel")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 180, 491, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.powerEntrylabel = QtWidgets.QLabel(self.centralwidget)
        self.powerEntrylabel.setGeometry(QtCore.QRect(40, 170, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.powerEntrylabel.setFont(font)
        self.powerEntrylabel.setObjectName("powerEntrylabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 190, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.Titletext.setText(_translate("mainWindow", "Recursion"))
        self.powerButton.setText(_translate("mainWindow", "Power"))
        self.catButton.setText(_translate("mainWindow", "Cat Ears"))
        self.alienButton.setText(_translate("mainWindow", "Alien Ears"))
        self.pushButton.setText(_translate("mainWindow", "Calculate"))
        self.firstEntrylabel.setText(_translate("mainWindow", "Number Entry"))
        self.powerEntrylabel.setText(_translate("mainWindow", "Power Entry"))
        self.label_2.setText(_translate("mainWindow", "(Only for Power Option)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
